version: '3'

services:
  postgresql15:
    image: postgres:15
    container_name: pgxls_postgresql15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword1234
      POSTGRES_DB: dvdrental
    ports:
      - "15432:5432"
